# Application Configuration
spring.application.name=MDD

#Server

server.port=3001
server.servlet.context-path=/api

# Database Configuration
spring.jpa.hibernate.ddl-auto=create
spring.datasource.url=jdbc:mysql://localhost:3306/mdd_social_network
spring.datasource.username=root
spring.datasource.password=rootam
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JWT Configuration
jwt.secret=XvthLtexI8j!0t@G877ydVIve$%U&oGuqQB@PjIAKfu^w4vb^@#F$482u3$@WEyq0cjq7hYxq7bS*u!qmHeUGRxx2@SfOP8lHGH5
jwt.expiration=86400000